// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package service_routing

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// IdempotencyRPCClient is the client API for IdempotencyRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IdempotencyRPCClient interface {
	Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
}

type idempotencyRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewIdempotencyRPCClient(cc grpc.ClientConnInterface) IdempotencyRPCClient {
	return &idempotencyRPCClient{cc}
}

func (c *idempotencyRPCClient) Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/innovationupstream.service.data.utility.idempotency.v1beta1.IdempotencyRPC/Set", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *idempotencyRPCClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/innovationupstream.service.data.utility.idempotency.v1beta1.IdempotencyRPC/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdempotencyRPCServer is the server API for IdempotencyRPC service.
// All implementations should embed UnimplementedIdempotencyRPCServer
// for forward compatibility
type IdempotencyRPCServer interface {
	Set(context.Context, *SetRequest) (*emptypb.Empty, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
}

// UnimplementedIdempotencyRPCServer should be embedded to have forward compatible implementations.
type UnimplementedIdempotencyRPCServer struct {
}

func (UnimplementedIdempotencyRPCServer) Set(context.Context, *SetRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Set not implemented")
}
func (UnimplementedIdempotencyRPCServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}

// UnsafeIdempotencyRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdempotencyRPCServer will
// result in compilation errors.
type UnsafeIdempotencyRPCServer interface {
	mustEmbedUnimplementedIdempotencyRPCServer()
}

func RegisterIdempotencyRPCServer(s grpc.ServiceRegistrar, srv IdempotencyRPCServer) {
	s.RegisterService(&IdempotencyRPC_ServiceDesc, srv)
}

func _IdempotencyRPC_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdempotencyRPCServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/innovationupstream.service.data.utility.idempotency.v1beta1.IdempotencyRPC/Set",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdempotencyRPCServer).Set(ctx, req.(*SetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdempotencyRPC_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdempotencyRPCServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/innovationupstream.service.data.utility.idempotency.v1beta1.IdempotencyRPC/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdempotencyRPCServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IdempotencyRPC_ServiceDesc is the grpc.ServiceDesc for IdempotencyRPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IdempotencyRPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "innovationupstream.service.data.utility.idempotency.v1beta1.IdempotencyRPC",
	HandlerType: (*IdempotencyRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Set",
			Handler:    _IdempotencyRPC_Set_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _IdempotencyRPC_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service/data/utility/idempotency/v1beta1/idempotency_service.proto",
}
