// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.1
// source: meta/reference/v1beta1/reference.proto

package reference

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReferenceType int32

const (
	ReferenceType_None     ReferenceType = 0
	ReferenceType_Internal ReferenceType = 1
	ReferenceType_External ReferenceType = 2
	ReferenceType_Owner    ReferenceType = 3
)

// Enum value maps for ReferenceType.
var (
	ReferenceType_name = map[int32]string{
		0: "None",
		1: "Internal",
		2: "External",
		3: "Owner",
	}
	ReferenceType_value = map[string]int32{
		"None":     0,
		"Internal": 1,
		"External": 2,
		"Owner":    3,
	}
)

func (x ReferenceType) Enum() *ReferenceType {
	p := new(ReferenceType)
	*p = x
	return p
}

func (x ReferenceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReferenceType) Descriptor() protoreflect.EnumDescriptor {
	return file_meta_reference_v1beta1_reference_proto_enumTypes[0].Descriptor()
}

func (ReferenceType) Type() protoreflect.EnumType {
	return &file_meta_reference_v1beta1_reference_proto_enumTypes[0]
}

func (x ReferenceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReferenceType.Descriptor instead.
func (ReferenceType) EnumDescriptor() ([]byte, []int) {
	return file_meta_reference_v1beta1_reference_proto_rawDescGZIP(), []int{0}
}

var File_meta_reference_v1beta1_reference_proto protoreflect.FileDescriptor

var file_meta_reference_v1beta1_reference_proto_rawDesc = []byte{
	0x0a, 0x26, 0x6d, 0x65, 0x74, 0x61, 0x2f, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65,
	0x2f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2f, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e,
	0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x29, 0x69, 0x6e, 0x6e, 0x6f, 0x76, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x75, 0x70, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x6d, 0x65, 0x74,
	0x61, 0x2e, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x62, 0x65,
	0x74, 0x61, 0x31, 0x2a, 0x40, 0x0a, 0x0d, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x0c,
	0x0a, 0x08, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08,
	0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x4f, 0x77,
	0x6e, 0x65, 0x72, 0x10, 0x03, 0x42, 0x48, 0x5a, 0x46, 0x67, 0x6f, 0x2e, 0x69, 0x6e, 0x6e, 0x6f,
	0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x75, 0x70, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x64,
	0x65, 0x76, 0x2f, 0x67, 0x6f, 0x2d, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d,
	0x65, 0x74, 0x61, 0x2f, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x2f, 0x76, 0x31,
	0x62, 0x65, 0x74, 0x61, 0x31, 0x3b, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_meta_reference_v1beta1_reference_proto_rawDescOnce sync.Once
	file_meta_reference_v1beta1_reference_proto_rawDescData = file_meta_reference_v1beta1_reference_proto_rawDesc
)

func file_meta_reference_v1beta1_reference_proto_rawDescGZIP() []byte {
	file_meta_reference_v1beta1_reference_proto_rawDescOnce.Do(func() {
		file_meta_reference_v1beta1_reference_proto_rawDescData = protoimpl.X.CompressGZIP(file_meta_reference_v1beta1_reference_proto_rawDescData)
	})
	return file_meta_reference_v1beta1_reference_proto_rawDescData
}

var file_meta_reference_v1beta1_reference_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_meta_reference_v1beta1_reference_proto_goTypes = []interface{}{
	(ReferenceType)(0), // 0: innovationupstream.meta.reference.v1beta1.ReferenceType
}
var file_meta_reference_v1beta1_reference_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_meta_reference_v1beta1_reference_proto_init() }
func file_meta_reference_v1beta1_reference_proto_init() {
	if File_meta_reference_v1beta1_reference_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_meta_reference_v1beta1_reference_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_meta_reference_v1beta1_reference_proto_goTypes,
		DependencyIndexes: file_meta_reference_v1beta1_reference_proto_depIdxs,
		EnumInfos:         file_meta_reference_v1beta1_reference_proto_enumTypes,
	}.Build()
	File_meta_reference_v1beta1_reference_proto = out.File
	file_meta_reference_v1beta1_reference_proto_rawDesc = nil
	file_meta_reference_v1beta1_reference_proto_goTypes = nil
	file_meta_reference_v1beta1_reference_proto_depIdxs = nil
}
